import pandas as pd
import io
from docx import Document
from datetime import datetime
from modules.logger_setup import logger

def create_excel(df):
    try:
        bio = io.BytesIO()
        with pd.ExcelWriter(bio, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name='Data')
        return bio.getvalue()
    except Exception as e:
        logger.error(f"Excel Error: {e}")
        return None

def create_docx(title, content):
    try:
        doc = Document()
        doc.add_heading(title, 0)
        doc.add_paragraph(f"Generated by RehaBeyond AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        for line in content.split('\n'):
            if line.startswith('### '): doc.add_heading(line.replace('### ', '').replace('*', ''), level=3)
            elif line.startswith('## '): doc.add_heading(line.replace('## ', '').replace('*', ''), level=2)
            elif line.startswith('# '): doc.add_heading(line.replace('# ', '').replace('*', ''), level=1)
            elif line.startswith('- ') or line.startswith('* '):
                clean_line = line[2:].replace('**', '').strip()
                if clean_line: doc.add_paragraph(clean_line, style='List Bullet')
            elif line.strip() == '': continue
            else: doc.add_paragraph(line.replace('**', ''))
        bio = io.BytesIO()
        doc.save(bio)
        return bio.getvalue()
    except Exception as e:
        logger.error(f"Word Error: {e}")
        return None

def generate_ris(df):
    ris = ""
    for _, row in df.iterrows():
        ris += "TY  - JOUR\n"
        ris += f"TI  - {row['Title']}\n"
        ris += f"JO  - {row['Journal']}\n"
        if row.get('Year'): ris += f"PY  - {row['Year']}\n"
        if row.get('DOI'): ris += f"DO  - {str(row['DOI']).replace('https://doi.org/', '')}\n"
        if row.get('Abstract'): ris += f"AB  - {str(row['Abstract']).replace(chr(10), ' ')}\n"
        if row.get('Authors'):
            for au in str(row['Authors']).split(","):
                if au.strip(): ris += f"AU  - {au.replace('et al.','').strip()}\n"
        if row.get('OA_Link') and pd.notna(row['OA_Link']): ris += f"UR  - {row['OA_Link']}\n"
        elif row.get('DOI'): ris += f"UR  - {row['DOI']}\n"
        ris += "ER  - \n\n"
    return ris.encode('utf-8-sig')
